### ISSUE TITLE
Update to use latest wiringpi ? 

### ISSUE THREAD

**Issue by rsmck** [Soarez/node-wiring-pi#4]
Are there any plans to update this to us the latest wiring-pi from git://git.drogon.net/wiringPi which has support for the Raspberry Pi 2 ( the current version uses the old github repository for wiringpi, which has not been updated in some time and does not work with the recent Pi :( )

**Comment by Soarez** [comment]
I'm sorry. I need to get myself a RPi2 and a free weekend.

**Comment by rsmck** [comment]
No need to apologise : )  ...  let me know if there's anything I can do, can provide remote SSH access to a Pi2 if it helps
